{
  "hash": "993f6e7c7e4cc0b629ac3fd807ea1129",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Day 1 & 2: Conceptual practice exercises - KEY\"\nsubtitle: \"Lines, rates of change, functions, exponentials & logs, and integrals\"\neditor_options:\n  chunk_output_type: console\n---\n\n::: {.callout-warning}\nThis page contains solutions. [Go to the exercises without solutions.](day1-day2-conceptual-exercises.qmd)\n:::\n\n::: {.callout-note}\nFor every exercise below, write your final answer as a **complete sentence**, including units, as if you were explaining it to someone unfamiliar with the data. \n:::\n\n## Exercise 1\n\nEnvironmental scientists model evapotranspiration (the combined loss of water from soil evaporation and plant transpiration) for a crop field. They believe evapotranspiration depends on: solar radiation, air temperature, and wind speed.\n\n(a) In this scenario, which variable is the output (dependent variable), and which are the inputs (independent variables)?\n(b) Write a sentence of the form \"[output] is a function of [input(s)]\" using the variable names.\n(c) Choose short notation (a letter or symbol) and units for each variable. Using your notation, write the function notation set-up for this relationship (you do not need an explicit formula).\n(d) Suppose a simplified model turns out to be:\n$$\nET(R,T,W) = 0.02R + 0.15T - 0.05W\n$$\nwhere $ET$ is evapotranspiration (mm/day), $R$ is solar radiation (W/m²), $T$ is air temperature (°C), and $W$ is wind speed (km/hr). Evaluate this model when $R=500$, $T=25$, and $W=10$, and state the result as a full sentence.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n**(a)** Evapotranspiration is the output (dependent variable). Solar radiation, air temperature, and wind speed are the inputs (independent variables).\n\n**(b)** \"Evapotranspiration is a function of solar radiation, air temperature, and wind speed.\"\n\n**(c)** For example: $ET$ = evapotranspiration (mm/day), $R$ = solar radiation (W/m²), $T$ = air temperature (°C), $W$ = wind speed (km/hr). *(Any reasonable, clearly-defined notation is fine!)*\n\n**(d)** $$ET(R, T, W) = [\\text{expression containing } R, T, \\text{ and } W]$$\n\n**(e)**\n$$\nET(500, 25, 10) = 0.02(500) + 0.15(25) - 0.05(10) = 10 + 3.75 - 0.5 = 13.25\n$$\n\n\"When solar radiation is 500 W/m², air temperature is 25°C, and wind speed is 10 km/hr, the model predicts an evapotranspiration rate of 13.25 mm per day.\"\n:::\n\n## Exercise 2\n\nA stream's water temperature increases as you move downstream from a shaded headwater spring. At a monitoring station 2 km downstream, the water temperature is 14°C. At a station 5 km downstream, the temperature is 20°C. Assume temperature increases linearly with distance downstream.\n\n(a) Find the equation for water temperature $T$ (°C) as a function of distance downstream $x$ (km).\n(b) Create a plot showing the line. Clearly label the axes, including units, and add a title.\n(c) What is the $y$-intercept of this line, and what does it mean in the context of the stream? Answer in a full sentence.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n**(a)** Using the two points $(2, 14)$ and $(5, 20)$:\n\n$$\nm = \\frac{20-14}{5-2} = \\frac{6}{3} = 2\n$$\n\nUsing point-slope form with $(2,14)$:\n$$\nT - 14 = 2(x-2) \\ \\Rightarrow \\ T = 2x + 10\n$$\n\n**(b)**\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](day1-day2-conceptual-exercises-key_files/figure-html/unnamed-chunk-1-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n**(c)** The $y$-intercept is $b = 10$.\n\n\"According to this model, the water at the very start of the stream (right at the headwater spring, 0 km downstream) is predicted to be 10°C.\"\n:::\n\n## Exercise 3\n\nResearchers plotted [dissolved oxygen (DO)](https://www.epa.gov/system/files/documents/2021-07/parameter-factsheet_do.pdf) concentration against water depth in a lake, and found the relationship was linear over the depth range sampled.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](day1-day2-conceptual-exercises-key_files/figure-html/unnamed-chunk-2-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n(a) Write the equation for dissolved oxygen, $DO$, as a function of depth.\n(b) Interpret the slope in a full sentence, including units.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n**(a)** The line passes through $(0, 9)$ and $(10, 3)$, so:\n\n- $y$-intercept: $9$\n- slope: $\\frac{3-9}{10-0} = \\frac{-6}{10} = -0.6$\n\n$DO(depth) = -0.6 \\cdot depth + 9$\n\n**(b)**\n\n\"For every additional meter of depth, dissolved oxygen concentration decreases by an average of 0.6 mg/L, starting from a surface concentration of about 9 mg/L.\"\n:::\n\n## Exercise 4\n\nThe city has begun a 20-day, round-the-clock grading and paving phase for a highway-widening project that cuts directly through the Westside neighborhood, a community that already bears a disproportionate share of the region's industrial pollution and truck traffic. In response, a community air-quality monitoring group tracked the additional fine particulate matter concentration, $P(t)$ (µg/m³ of PM2.5 above baseline), in the neighborhood's air over the 20 days of that construction phase.\n\n:::: {.columns}\n::: {.column width=\"35%\"}\n| $t$ (days) | $P(t)$ (µg/m³) |\n|:---:|:---:|\n| 2  | 14.4 |\n| 6  | 33.6 |\n| 10 | 40.0 |\n| 14 | 33.6 |\n| 18 | 14.4 |\n:::\n\n::: {.column width=\"65%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](day1-day2-conceptual-exercises-key_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' width=95%}\n:::\n:::\n\n:::\n::::\n\n(a) Calculate the average rate of change in additional PM2.5 concentration between day 2 and day 6.\n(b) Write your answer as a full sentence, with units, without overstating certainty.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n$$\n\\text{average rate of change} = \\frac{P(6) - P(2)}{6-2} = \\frac{33.6 - 14.4}{4} = \\frac{19.2}{4} = 4.8 \\ \\frac{\\mu\\text{g/m}^3}{\\text{day}}\n$$\n\nBetween day 2 and day 6 of the grading phase, additional PM2.5 concentration in the Westside neighborhood increased by an average of 4.8 µg/m³ per day.\n:::\n\n## Exercise 5\n\nSince 2010, a mountain glacier has been losing volume at an accelerating pace as regional temperatures rise. Researchers model the cumulative ice volume lost, $V(t)$ (in km³), since monitoring began, as:\n\n$$\nV(t) = 0.5t^2 + 2t\n$$\n\nwhere $t$ is years since 2010.\n\n(a) Use differentiation rules to find $V'(t)$.\n(b) Evaluate $V'(5)$. What does this value mean in the context of the glacier? State it as a full sentence, with units.\n(c) Now calculate the *average* rate of ice loss between $t=4$ and $t=8$.\n(d) Are the values from (b) and (c) the same? In your own words, explain conceptually why an \"average\" rate of change over an interval doesn't have to match the \"instantaneous\" rate of change at a single point within it.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n**(a)** Using the power rule and sum rule:\n$$\nV'(t) = t + 2\n$$\n\n**(b)**\n$$\nV'(5) = 5 + 2 = 7 \\ \\frac{\\text{km}^3}{\\text{year}}\n$$\n\n> \"In 2015 (five years after monitoring began), the glacier was losing ice at an instantaneous rate of about 7 km³ per year.\"\n\n**(c)**\n$$\nV(4) = 0.5(4)^2+2(4) = 16, \\qquad V(8) = 0.5(8)^2+2(8) = 48\n$$\n$$\n\\text{average rate of change} = \\frac{V(8)-V(4)}{8-4} = \\frac{48-16}{4} = 8 \\ \\frac{\\text{km}^3}{\\text{year}}\n$$\n\n**(d)** The two values are close, but not the same (7 vs. 8 km³/year). The average rate of change smooths the ice loss out over the entire 4-year window from $t=4$ to $t=8$, while the instantaneous rate captures the exact pace of loss at the single moment $t=5$. \n:::\n\n## Exercise 6\n\nAfter restoring a section of coastal wetland, ecologists measure the rate at which the wetland absorbs stormwater runoff, $r(t)$ (in m³/hour), throughout a 24-hour storm. The graph below shows this absorption rate over time. Partway through the storm, the monitoring sensor lost power and went offline between hour 10 and hour 14 (shaded region in the graph) — but you still need to report an estimate of the total volume of stormwater absorbed over the full 24-hour storm.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](day1-day2-conceptual-exercises-key_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n(a) What does the *area under this curve* represent, in words? Be sure to include units.\n(b) Looking at the shape of the graph (without calculating anything), during which 6-hour window — hours 0–6, 6–12, 12–18, or 18–24 — do you expect the *largest volume* of stormwater to have been absorbed? Explain your reasoning.\n(c) Describe how you would handle the sensor gap when estimating the total area under the curve. What assumption(s) would you have to make, and how would the location of this particular gap affect your confidence in the final estimate?\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n**(a)** The area under the rate curve represents the **total volume of stormwater absorbed by the wetland** over that time period, in m³ (rate in m³/hr $\\times$ time in hr = volume in m³).\n\n**(b)** Hours 6–12. The curve is highest and covers the most area in that window, since the absorption rate peaks around hour 9 — the middle of the storm, when the ground is saturated and inflow is greatest.\n\n**(c)** Since there's no direct measurement between hour 10 and hour 14, we'd have to interpolate — for example, connecting the last known point (hour 10) to the first known point (hour 14) with a straight line, and using that as our best guess for the missing area. This assumes the rate changed smoothly and roughly monotonically across the gap.\n\nThat assumption is riskier here than it would be for an arbitrary gap, because this particular gap covers the storm's peak — the point where the true curve is doing the most curving. A straight-line interpolation would cut across that peak and likely *underestimate* the true absorption rate for most of the gap, so our total volume estimate is probably a bit too low, and we should be less confident in it than we would be if the same size gap had fallen during a flatter part of the storm.\n:::\n\n## Exercise 7\n\nForestry officials discover an invasion of an invasive insect in a county park. They estimate the insect population grows exponentially, following $N(t) = N_0 e^{rt}$, where $N_0$ is the initial number of egg masses counted per hectare, and $t$ is time in years since detection.\n\nAt detection ($t=0$), officials count $N_0 = 150$ egg masses per hectare. Four years later, the count has grown to $400$ egg masses per hectare.\n\n(a) Solve for the growth rate $r$.\n(b) Forestry regulators will impose a mandatory quarantine zone if the population reaches $5{,}000$ egg masses per hectare. Using your value of $r$, solve for the time $t$ at which this threshold will be reached.\n(c) State your answer to (b) as a full sentence.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n**(a)**\n$$\n\\begin{aligned}\n400 &= 150e^{4r} \\\\\n\\frac{400}{150} &= e^{4r} \\\\\n\\ln\\!\\left(\\frac{400}{150}\\right) &= 4r \\\\\nr &= \\frac{\\ln(2.667)}{4} \\approx 0.245\n\\end{aligned}\n$$\n\n**(b)**\n$$\n\\begin{aligned}\n5000 &= 150e^{0.245t} \\\\\n\\frac{5000}{150} &= e^{0.245t} \\\\\n\\ln(33.33) &= 0.245t \\\\\nt &= \\frac{\\ln(33.33)}{0.245} \\approx 14.3\n\\end{aligned}\n$$\n\n**(c)**\n\nIf the current growth trend continues, the insect population is expected to reach the quarantine threshold of 5,000 egg masses per hectare about 14.3 years after it was first detected.\n:::\n\n\n*All the functions and example data are synthetic and were generated with the aid of Claude Code for the purpose of this session.*",
    "supporting": [
      "day1-day2-conceptual-exercises-key_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}